services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: whatsapp_mongodb
    environment:
      MONGO_INITDB_DATABASE: whatsapp_multi_tenant
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - whatsapp_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: whatsapp_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - whatsapp_network

  # WAHA WhatsApp API
  waha:
    image: devlikeapro/waha
    container_name: whatsapp_waha
    ports:
      - '3001:3000'
    environment:
      - WHATSAPP_DEFAULT_ANSWER=Hello! This is a WhatsApp API service.
      - WHATSAPP_SESSION_STORE_TYPE=file
      - WHATSAPP_SESSION_STORE_PATH=/app/sessions
    volumes:
      - waha_sessions:/app/sessions
    networks:
      - whatsapp_network

volumes:
  mongodb_data:
  redis_data:
  waha_sessions:

networks:
  whatsapp_network:
    driver: bridge
